apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cnvrg-nomex-{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
