apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnvrg-operator
  namespace: cnvrg-infra
  labels:
    control-plane: cnvrg-operator
spec:
  selector:
    matchLabels:
      control-plane: cnvrg-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: cnvrg-operator
    spec:
      serviceAccountName: cnvrg-operator
      containers:
      - image: controller:latest
        command:
          - /opt/app-root/cnvrg-operator
          - run
          - --max-concurrent-reconciles
          - "3"
          - --deploy-depended-crds
          - "true"
        name: cnvrg-operator
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
