apiVersion: v2
name: cnvrg-mlops-platform
description: A cnvrg.io operator chart for K8s
type: application
version: 5.0.0
appVersion: 1.2.3
dependencies:
  - name: nomex
    version: 1.0.0
    repository: https://charts.slim.cnvrg.io/cnvrg
    condition: nomex.enabled

