apiVersion: mlops.cnvrg.io/v1
kind: CnvrgApp
metadata:
  name: cnvrg-app
spec:
  clusterDomain: "{{ .Values.clusterDomain }}"
  imageHub: {{ .Values.imageHub }}
  controlPlane:
    image: "{{.Values.controlPlane.image}}"
    cnvrgScheduler:
      enabled: true
    hyper:
      enabled: true
      image: hyper-server:latest
    nomex:
      enabled: true
      image: nomex:v1.0.0
    objectStorage:
      type: minio
      bucket: cnvrg-storage
      region: eastus
      accessKey: ""
      secretKey: ""
      endpoint: ""
      azureAccountName: ""
      azureContainer: ""
      gcpSecretRef: gcp-storage-secret
      gcpProject: ""
    searchkiq:
      enabled: true
    sidekiq:
      enabled: true
    smtp:
      server: ""
      port: 587
      username: ""
      password: ""
      domain: ""
      opensslVerifyMode: ""
      sender: "info@cnvrg.io"
    systemkiq:
      enabled: true
    webapp:
      enabled: true
  dbs:
    es:
      enabled: true
      image: cnvrg-es:v7.8.1.a1-dynamic-indices
      elastalert:
        enabled: true
        image: elastalert:3.0.0-beta.1
      kibana:
        enabled: true
        image: kibana-oss:7.8.1
    minio:
      image: minio:RELEASE.2021-05-22T02-34-39Z
      enabled: true
    pg:
      enabled: true
      image: postgresql-12-centos7:latest
    prom:
      enabled: true
      image: prometheus:v2.37.1
      grafana:
        enabled: true
        image: grafana-oss:9.1.6
    redis:
      enabled: true
      image: cnvrg-redis:v3.0.5.c2
  networking:
    https:
      enabled: false
    ingress:
      type: ingress
  registry:
    name: cnvrg-app-registry
    url: docker.io
    user: ""
    password: ""
  sso:
    enabled: false
    authz:
      enabled: false
      image: proxy:v1.0.1
    central:
      enabled: true
      adminUser: ""
      provider: ""
      emailDomain: ["*"]
      clientId: ""
      clientSecret: ""
      oidcIssuerUrl: ""
      scope: "openid email profile"
      insecureOidcAllowUnverifiedEmail: true
      whitelistDomain: ""
      cookieDomain: ""
      groupsAuth: false
    jwks:
      enabled: false
      image: jwks:latest

