{{- if or (eq .Values.spec "allinone") (eq .Values.spec "ccp") }}
---
apiVersion: mlops.cnvrg.io/v1
kind: CnvrgApp
metadata:
  name: cnvrg-app
  namespace: {{ template "spec.cnvrgNs" . }}
spec:
  clusterDomain: "{{ .Values.clusterDomain }}"
  clusterInternalDomain: "{{.Values.clusterInternalDomain}}"
  imageHub: {{ .Values.imageHub }}
  cri: "{{ .Values.cri }}"
  {{- include "spec.labelsAndAnnotations" . | indent 2 }}
  {{- include "spec.controlPlane" . | indent 2 }}
  {{- include "spec.registry" . | indent 2 }}
  {{- include "spec.app_dbs" . | indent 2 }}
  {{- include "spec.logging_app" . | indent 2 }}
  {{- include "spec.monitoring_app" . | indent 2 }}
  {{- include "spec.networking_app" . | indent 2 }}
  {{- include "spec.sso" . | indent 2 }}
  {{- include "spec.tenancy" . | indent 2 }}
---
{{- end }}