kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnvrg-operator
  namespace: {{ template "spec.cnvrgNs" . }}
subjects:
  - kind: ServiceAccount
    name: cnvrg-operator
    namespace: {{ template "spec.cnvrgNs" . }}
roleRef:
  kind: ClusterRole
  name: cnvrg-operator
  apiGroup: rbac.authorization.k8s.io
