apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnvrg-operator
  namespace: {{ template "spec.cnvrgNs" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "endpoints"
      - "events"
      - "namespaces"
      - "persistentvolumeclaims"
      - "pods"
      - "secrets"
      - "serviceaccounts"
      - "services"
      - "persistentvolumes"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
      - "customresourcedefinitions.apiextensions.k8s.io"
    verbs:
      - "*"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
      - "rolebindings"
      - "roles"
    verbs:
      - "*"
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "deployments/finalizers"
      - "ingresses"
      - "replicasets"
      - "statefulsets"
    verbs:
      - "*"
  - apiGroups:
      - "authentication.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
      - verticalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - "config.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "extensions"
    resources:
      - "daemonsets"
      - "deployments"
      - "deployments/finalizers"
      - "ingresses"
      - "replicasets"
      - "statefulsets"
    verbs:
      - "*"
  - apiGroups:
      - "install.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "servicemonitors"
    verbs:
      - "get"
      - "create"
      -  "patch"
  - apiGroups:
      - "networking.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "policy"
    resources:
      - "poddisruptionbudgets"
    verbs:
      - "*"
  - apiGroups:
      - "rbac.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "security.istio.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - "apiservices"
    verbs:
      - "*"
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - "storageclasses"
    verbs:
      - "get"
      - "create"
      - "patch"
      - "delete"
      - "list"