apiVersion: mlops.cnvrg.io/v1
kind: CnvrgApp
metadata:
  name: cnvrg-app
  namespace: {{ template "spec.cnvrgNs" . }}
spec:
  clusterDomain: {{ .Values.clusterDomain }}
  infraNamespace: {{ .Values.infraNamespace }}
  {{- include "spec.registry" . | indent 2 }}
  {{- include "spec.storage" . | indent 2 }}
  {{- include "spec.sso" . | indent 2 }}
  {{- include "spec.logging_infra" . | indent 2 }}
  {{- include "spec.monitoring_infra" . | indent 2 }}
  {{- include "spec.networking_infra" . | indent 2 }}