{{- if ne .Values.appClusterDomain ""}}
apiVersion: mlops.cnvrg.io/v1
kind: CnvrgApp
metadata:
  name: cnvrg-app
  namespace: {{ template "spec.cnvrgNs" . }}
spec:
  clusterDomain: {{ .Values.appClusterDomain }}
  {{- include "spec.controlPlane" . | indent 2 }}
  {{- include "spec.registry" . | indent 2 }}
  {{- include "spec.dbs" . | indent 2 }}
  {{- include "spec.logging_app" . | indent 2 }}
  {{- include "spec.monitoring_app" . | indent 2 }}
  {{- include "spec.networking_app" . | indent 2 }}
  {{- include "spec.sso" . | indent 2 }}
{{- end }}