####################################### Install hooks #######################################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "cnvrg-bootstrap"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cnvrg-bootstrap"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "batch"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - mlops.cnvrg.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cnvrg-bootstrap"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "cnvrg-bootstrap"
subjects:
  - kind: ServiceAccount
    name: "cnvrg-bootstrap"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: cnvrg-bootstrap
      terminationGracePeriodSeconds: 1
      containers:
        - name: cnvrgapp
          image: docker.io/cnvrg/cnvrg-tools:v0.3
          args:
            - /bin/bash
            - -c
            - |
              echo "running post install"
              {{- if ne .Values.spec "infra" }}
              _term() {
                echo "Caught SIGTERM signal!"
                exit
              }
              trap _term SIGTERM
              echo "waiting for cnvrgapp will finish installation. . . ";
              while [[ $(kubectl get cnvrgapp cnvrg-app -n {{ template "spec.cnvrgNs" . }} -o=jsonpath='{.status.status}') != READY ]]; do
                sleep 0.1
              done
              echo "installation completed. . . ";
              kubectl delete job post-install -n {{ template "spec.cnvrgNs" . }}
              {{- end }}
      restartPolicy: Never
