
{{- if eq .Values.spec "allinone"}}
{{/* assuming namespace tenancy disabled, deploy the operator + cnvrg infra + cnvrg controle plan  */}}
{{ template "operator" . }}
{{ template "infra" . }}
{{ template "ccp" . }}

{{- else if eq .Values.spec "infra"}}
{{/* assuming namespace tenancy enabled, deploy only the operator + cnvrg infra */}}
{{ template "operator" . }}
{{ template "infra" . }}

{{- else if eq .Values.spec "ccp"}}
{{/* assuming namespace tenancy enabled, deploy only cnvrg control plane */}}
{{ template "ccp" . }}

{{- end }}