apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: operator-pull-secret
  namespace: {{ template "spec.cnvrgNs" . }}
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.registry.url .Values.registry.user .Values.registry.password (printf "%s:%s" .Values.registry.url .Values.registry.user .Values.registry.password | b64enc) | b64enc }}

