kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnvrg-operator
  namespace: {{ template "spec.cnvrgNs" . }}
subjects:
- kind: ServiceAccount
  name: cnvrg-operator
roleRef:
  kind: Role
  name: cnvrg-operator
  apiGroup: rbac.authorization.k8s.io

