apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastorageprovisioner
  namespace: {{ .Release.Namespace }}
  labels:
    app: metastorageprovisioner
    component: metastorageprovisioner
spec:
  selector:
    matchLabels:
      app: metastorageprovisioner
      component: metastorageprovisioner
  template:
    metadata:
      labels:
        app: metastorageprovisioner
        component: metastorageprovisioner
    spec:
      serviceAccountName: cnvrg-metastorageprovisioner
      containers:
      - name: metastorageprovisioner
        imagePullPolicy: Always
        {{- if .Values.version }}
        image: "{{.Values.imageHub}}/cnvrg-operator:{{.Values.version}}"
        {{- else if .Values.operatorVersion }}
        image: "{{.Values.imageHub}}/cnvrg-operator:{{.Values.operatorVersion}}"
        {{- else }}
        image: "{{.Values.imageHub}}/cnvrg-operator:{{.Chart.Version}}"
        {{- end }}
        command:
          - /opt/app-root/metastorageprovisioner
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
