apiVersion: v1
kind: Service
metadata:
  name: cnvrg-operator-admission
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: cnvrg-admission-controller