# permissions for end users to view cnvrginfras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnvrginfra-viewer-role
rules:
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrginfras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrginfras/status
  verbs:
  - get
