# permissions for end users to view cnvrgapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnvrgapp-viewer-role
rules:
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrgapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrgapps/status
  verbs:
  - get
