# permissions for end users to edit cnvrginfras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnvrginfra-editor-role
rules:
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrginfras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - cnvrginfras/status
  verbs:
  - get
