apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnvrg-operator-role
  namespace: cnvrg
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - mlops.cnvrg.io
    resources:
      - '*'
    verbs:
      - '*'