imageHub: docker.io
image: mpioperator/mpi-operator:v0.5
kubectlDeliveryImage: mpioperator/kubectl-delivery:v0.5
imagePullSecretRef: cnvrg-app-registry
scc: false
registry:
  name: "mpi-private-registry"
  url: "docker.io"
  user: ""
  password: ""