apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: uac
  labels:
    app: uac
webhooks:
  - name: foo.bar.test.local
    clientConfig:
      url: https://foo.bar.test.local:8080/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVRTh0UHQ3dEZkUyt3M0ZGVWNNUW1PeU0xZ3JFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXpNVEl4TVRBNE1qWXdObG9ZRHpJeApNak14TVRFM01EZ3lOakEyV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN0bG9TZUg1M25GUmFVUHdvSDRWRWRoTlNmQUZ4a3B1UFMKT0lDRGFLbWc2UXVLazV1d1RmMlZjQUxzWnA3blBtcGJtRUFWY1MzUk9hSVFjam9qclNkTS9ON1NRQWVtVnUvWAoxRitLT1VwVVlaODd3WVlvZ0NBU0lnNENZUXpJSU80MVJPVjlDS0JXRm1ncWtsRmUrRU9kajUxOW8wTjE4STZuCjZidEZvWTNOL0lDRmNiYUwrbjVOM0FsM1hOWUNRVzgxOWNLNmU5SDdLQVBFQlpCaEZDTTdDR0tSbXFxU1Z5UHgKTEhuRGQrb3o1NW1lV3Uzelkvd3JrR0NWVnplSHNnb1E4UE04cTd4eGIwRUR3V0R2MENDUFlvVnZDTVFXT2NYRgpINDJUSDhrNnR5ajdvOHhUcURWbTNBc0YzWXBuV3RSdUVxU1FQRUZuK3hqU3NVUzRRMmRqQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUkVYTVh0ZVdBVG82OVlwNTZZWmxEdWU3U3gyakFmQmdOVkhTTUVHREFXZ0JSRVhNWHQKZVdBVG82OVlwNTZZWmxEdWU3U3gyakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCL1FzSzNFTnNBa1BBbENmb2YrS2NLY0hCOHIrNXk0VGk1aXhpeXJyRENOSmJXWHpSblpWSUtHZW1SCmJ4aFhVT0xZaTc0SkFnUFdTb0V6QWRjaU90U2MrKzVvT2ZsN1BtOW9vN2g1SnlwVm5QdmtxZEthQmVPbEJ6clEKZEJRTWtPZXgwNFNnUjY3dHlOTUUvOFFEWWUrbkJ4bkVkNzd1ZXpTTWViZlZteEZvRFpjN1JZQ0tLaU54TzRieAppNEd0KzNvV25pY3RmZmF1cEkzcUlQZEtwckMrSUo3MEsvUCtmTG1xaU1DL0FDcDFLa3ZRSFZsZm92WmtFV3QvCkdkN0tqUTgzaG9OWDQzWlE1NUdBZDlvWFRhb3BTR3pBZWE4U09hSFY1bEdnS1RkNEJnWm5hSGIvVTRtdUduR3kKUG5IbTJGa3JNZks2aG5Xd1lWdU8yVjRkeHZiRAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["oauthaccesstokens"]
    failurePolicy: Ignore
