apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cnvrg-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Cnvrg App
      kind: CnvrgApp
      name: cnvrgapps.mlops.cnvrg.io
      version: v1
    - displayName: Cnvrg Infra
      kind: CnvrgInfra
      name: cnvrginfras.mlops.cnvrg.io
      version: v1
  description: Cnvrg Operator
  displayName: Cnvrg Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - ml
  links:
  - name: Cnvrg Operator
    url: https://cnvrg-operator.domain
  maturity: alpha
  provider:
    name: cnvrg.io
    url: https://cnvrg.io
  version: 0.0.0
