apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cvat-redis
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cvat-redis
subjects:
  - kind: ServiceAccount
    name: cvat-redis