apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cvat-redis
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
