apiVersion: v1
kind: Service
metadata:
  name: cvat-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: cvat-redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: cvat-redis