{
 "title": "Cnvrg Job",
 "description": "Cnvrg Job",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cnvrg_jobs_container_cpu_usage, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cnvrg_jobs_container_cpu_usage{pod_name=~\"$pod*.+\"} / 1000",
     "legendFormat": "{{container_name}} cpu usage"
    },
    {
     "expr": "cnvrg_jobs_container_cpu_request{pod_name=~\"$pod*.+\"} / 1000",
     "legendFormat": "{{container_name}} cpu request"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cnvrg_jobs_container_cpu_throttling_percentage{pod_name=~\"$pod*.+\"}",
     "legendFormat": "{{container_name}} cpu throttling"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "cnvrg_jobs_container_memory_usage{pod_name=~\"$pod*.+\"}",
     "legendFormat": "{{container_name}} memory usage"
    },
    {
     "expr": "cnvrg_jobs_container_memory_request{pod_name=~\"$pod*.+\"}",
     "legendFormat": "{{container_name}} memory request"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(cnvrg_jobs_container_network_received_bytes{pod_name=~\"$pod*.+\", interface=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(cnvrg_jobs_container_network_sent_bytes{pod_name=~\"$pod*.+\", interface=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}