apiVersion: v1
kind: Service
metadata:
  name: {{cnvrgApp.svcName}}
  namespace: {{ ansible_operator_meta.namespace }}
  labels:
    app: {{cnvrgApp.svcName}}
spec:
  {% if networking.ingressType == "nodeport" %}
  type: NodePort
  {% endif %}
  ports:
  - port: {{cnvrgApp.port}}
    {% if networking.ingressType == "nodeport" %}
    nodePort: {{ cnvrgApp.nodePort }}
    {% endif %}
  selector:
    app: {{cnvrgApp.svcName}}