apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{monitoring.grafana.svcName}}"
  namespace: "{{ansible_operator_meta.namespace}}"
spec:
  hosts:
  - "{{(monitoring.grafana.svcName + "." + clusterDomain).split(':')[0] }}"
  gateways:
  - "{{networking.istio.gwName}}"
  http:
  - retries:
      attempts: {{ networking.istio.retriesAttempts | default ('5') }}
      perTryTimeout: {{ networking.istio.perTryTimeout | default ('180s') }}
    timeout: {{ networking.ingress.timeout | default ('900s') }}
    route:
    - destination:
        host: "{{monitoring.grafana.svcName +"."+ ansible_operator_meta.namespace + ".svc.cluster.local" }}"
        port:
          number: {{monitoring.grafana.port}}
