apiVersion: v1
kind: Service
metadata:
  name: cnvrg-operator-admission
  namespace: cnvrg-shim
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cnvrg-operator-admission
  namespace: cnvrg-shim
subsets:
- addresses:
  - ip: 85.65.199.201
  ports:
  - port: 8080
    protocol: TCP