apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "cnvrg-operator-admission.cnvrg-shim.svc"
webhooks:
  - name: "cnvrg-operator-admission.cnvrg-shim.svc"
    rules:
      - apiGroups: [ "mlops.cnvrg.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "cnvrgapps" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "cnvrg-shim"
        name: "cnvrg-operator-admission"
        path: "/aicloud/domain-discovery"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1VENDQXFHZ0F3SUJBZ0lVQkhTY3VXUjBWWjBHRjRiWS9uOTRQL3ZrYzRvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNTVXd4RGpBTUJnTlZCQWdNQlVoaGFXWmhNUXN3Q1FZRFZRUUhEQUpTU0RFTwpNQXdHQTFVRUNnd0ZZMjUyY21jeEZqQVVCZ05WQkFzTURYQnNZWFJtYjNKdExYUmxZVzB4RnpBVkJnTlZCQU1NCkRuSnZiM1F1Ykc5allXeG9iM04wTUNBWERUSXpNVEl4TWpBNU16UTBORm9ZRHpJeE1qTXhNVEU0TURrek5EUTAKV2pCck1Rc3dDUVlEVlFRR0V3SkpUREVPTUF3R0ExVUVDQXdGU0dGcFptRXhDekFKQmdOVkJBY01BbEpJTVE0dwpEQVlEVlFRS0RBVmpiblp5WnpFV01CUUdBMVVFQ3d3TmNHeGhkR1p2Y20wdGRHVmhiVEVYTUJVR0ExVUVBd3dPCmNtOXZkQzVzYjJOaGJHaHZjM1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzIKWnAyS2M1bDB6M0xRWWNiWVNBYjNJRHFhMzROWmV1bnNXSGJsakxqalZVRlU5a1FLdXhRcmVUT2NrOHJGTVdzeAo1TlloTkk0M2Npb0xkb2pWM1ZwUXNIYW93SlhqYko4NUFEekh3WXdKMlpKazNoMWJLeWpCL1ZYYlZzTVc5K2xQClZESSszeHFpdlJQZEhCajVyYTI0Vi9zQis1REVQdWZyN1NtWTBIVjlFUWordW5xYnd3UWFHZ1hSdkhueHVEUTgKdFJMR1pkeXNHSjdodXF3RVdpUmN5RDFjNTFvcHYwamxqL1lkR1BYRVdLQmtUWVhEZ3pyV1BZZ2V4QXErSzdndApQUzBrZStaUWF0Y29KWkhJRHVzNStOejFkOHcrL0g0b0FCUXBtNFNJRTJEMTJCbG5LMTlEb3FRZENPL3VVaHhMCkhxSm1sZDJLKzRzbStiOUJ1VE9MQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRbTFPelo3dDlmUlQzOXdheUsKa3MxSnVibmhhVEFmQmdOVkhTTUVHREFXZ0JRbTFPelo3dDlmUlQzOXdheUtrczFKdWJuaGFUQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNyK3czbnArQldLV3ZkZzhRNzN1NWpPaWNWCkN2UkxNQlU2a0lRbDlIZDJJSTk4UHJaVkxOOHJ6SGhmSTY5TTZJcFh4bU55TURud2ZSZEJYc0Y1a2s2a1Jpb0MKNjNRd1FMUCtlVllmbDMrQitkYkhhbklsTFZycTJXRUdJczFKQUpyMklOSEZGUDFtMHpIQndYSHZEb3BVRmlDbgpwcDFvVktKNGpBa3Y3WHI0aStSQUQ2NWtNeXA1SjR0RlplVDFQYzA5UXFidk1XNXFLb3BXMWJLRnhmRWpRdkJsCjNOVE5rL3luT1hkTDRpYXZpMlhNblVBVEU0ZFVHbFhQaUhXdmJ4REwzdUQ4L3gvZ0pGQlFFMmRFYy9Ub2Y0a2cKRUtxTy8yNEJTQ2dGUW5UdzBKR3BucUFXR3FRaFBzR1FWY3p4bEY1OHN5blRxWkdsWmFVKytTOXJONEVsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: 5