apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "cnvrg-operator-admission.cnvrg-shim.svc"
webhooks:
  - name: "cnvrg-operator-admission.cnvrg-shim.svc"
    rules:
      - apiGroups: [ "mlops.cnvrg.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "cnvrgapps" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "cnvrg-shim"
        name: "cnvrg-operator-admission"
        path: "/aicloud/domain-discovery"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lDQm5vd0RRWUpLb1pJaHZjTkFRRUxCUUF3UHpFTE1Ba0dBMVVFQmhNQ1NVd3gKRnpBVkJnTlZCQW9URG1OdWRuSm5MV0ZwTFdOc2IzVmtNUmN3RlFZRFZRUURFdzV5YjI5MExteHZZMkZzYUc5egpkREFlRncweU16RXlNakV4TWpNeE1UQmFGdzB6TXpFeU1qRXhNak14TVRCYU1EOHhDekFKQmdOVkJBWVRBa2xNCk1SY3dGUVlEVlFRS0V3NWpiblp5WnkxaGFTMWpiRzkxWkRFWE1CVUdBMVVFQXhNT2NtOXZkQzVzYjJOaGJHaHYKYzNRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGOXVzeTYrUmhteERNbmZJUApnMFdaT0pPN3FEVU9EN2pEaDNHd0hEak11c2VTRGpUekZoTmM3b210QXBaRVlSVHJ4ekV0YmwyRmo0UTF6VncrCmdwWkV1eDd5MHhPeHZscVlXUmEraUdvUFB2VkpiM0dJb1hBTGJBcUlLL29CMmt4SmNoMjVvRnlHc01qQnVFNVYKMFNzMEp6bHNXZ0Y5Q2JRd1Bxa1I0V3BxSW5SRWlIRVNRK0hjdzFsKytyTE9pcUxVRE5mK1Erd3Z6Z094U3MxWgpLc0hOQytpR2hHK1JKKzFIdEEvL21lRXBYdUgwTUZjMnc4VWsrM2JQTE5JSytkUkE1b2ZoWE83eUVISWxMK2RNCk1KcmJrVnVLTE52UGtVZm5WOVQ4M1VGK2pteWxJR0JqdEp6ZlJZVm1qUzc4WmNheVZtVjBPV1RSQVh5ME9OZzAKMDk0WEFnTUJBQUdqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVNllTcjVZbm81SDZNCnZwNSt1S0tVRGNrbEpFVXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTVNwUGZ2bE9UNkd2eUl5OEdoVFVFQzMKVmNVemFvdHlmZUtCSWd4ZzBYSFludmRKbmIxcmUyYUgxZUxxa1BGQk50MDh4L09SZVlDQ3k3T0FGcWtXT1dWTQpwMHk0bG13YW93VVNIUGliNXluZXY5ZHF4UmNTa09yaFpqNHp3YXdzTTUxNUhTYlBtM1pscVNhTGkxVUtUSXg5Cm1JT3d1YWZLUHBraDhUWVViKzN3Q3B6RmU5RXBCZ29hL3QrYWs3UEs3U1BWYWJOaytnZGxjTkRpZGh3Vk41c1UKQkQzT3NvQ3VPNGZ5T2ZWT0d1UzloOVE3eDBDUk85d09Kb0VWZDVUTnQ2em9jTlp5RFpkUEFuRjdTUVo4SEkregpYUllxLzNySWxIQVk2eGlLODh6R2hTNnFLaks5alc4WEVmT0JoNE1oY0FmRGFZVEp5WEFSUXE2eE16T01uWXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: 5